config/routes.rb
Rails.application.routes.draw do
  
  
 
 
 

  devise_for :users

  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    resource :goods, only: [:create, :destroy]
    resource :bads, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  root 'tweets#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bad.rb
class Bad < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/good.rb
class Good < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tweet_tags, dependent: :destroy
    has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :favorites
    has_many :goods
    has_many :bads
    mount_uploader :image, ImageUploader
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
    def gooded_by?(user)
        goods.where(user_id: user.id).exists?
    end
    def baded_by?(user)
        bads.where(user_id: user.id).exists?
    end        
    has_many :tweet_tags, dependent: :destroy
    has_many :tags, through: :tweet_tags

    default_scope -> { order(created_at: :desc) }
    
    has_many :comments, dependent: :destroy
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
    belongs_to :tweet
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :name, presence: true
         
   has_many :tweets
   has_many :favorites
   has_many :favorite_tweets, through: :favorites, source: :tweet

   has_many :goods
   has_many :good_tweets, through: :goods, source: :tweet
   has_many :bads
   has_many :bad_tweets, through: :bads, source: :tweet
   
   has_many :comments, dependent: :destroy

end

app/controllers/bads_controller.rb
class BadsController < ApplicationController
  def create
    bad = current_user.bads.build(tweet_id: params[:tweet_id])
    bad.save
    redirect_to tweets_path

    if @good= Good.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
      @good.destroy
    end
    if @favorite= Favorite.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
      @favorite.destroy
    end
  end

  def destroy
    bad = Bad.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    bad.destroy
    redirect_to tweets_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    @comment = tweet.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    # こう記述することで、「current_userに関連したFavoriteクラスの新しいインスタンス」が作成可能。
    # つまり、favorite.user_id = current_user.idが済んだ状態で生成されている。
    # buildはnewと同じ意味で、アソシエーションしながらインスタンスをnewする時に形式的に使われる。
    favorite = current_user.favorites.build(tweet_id: params[:tweet_id])
    favorite.save
    redirect_to tweets_path

    
    if @good= Good.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
      @good.destroy
    end
    if @bad= Bad.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
      @bad.destroy
    end
  end

  def destroy
    favorite = Favorite.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    favorite.destroy
    redirect_to tweets_path
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def create
    good = current_user.goods.build(tweet_id: params[:tweet_id])
    good.save
    redirect_to tweets_path

    if @bad= Bad.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
      @bad.destroy
    end
    if @favorite= Favorite.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
      @favorite.destroy
    end


  end

  def destroy
    good = Good.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    good.destroy
    redirect_to tweets_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  def new
    @tweet = Tweet.new
   
  end

  def index
    @tweets = Tweet.all
    @q = Tweet.ransack(params[:q])
    @tweets = params[:tag_id].present? ? Tag.find(params[:tag_id]).tweets : Tweet.all
    @tweets = @q.result(distinct: true)||tag
  end

  def show
    @tweet = Tweet.find(params[:id])
    @user = @tweet.user
    @comments = @tweet.comments
    @comment = @tweet.comments.build
  end

  def create
    @tweet = Tweet.new(tweet_params)  # フォームから送られてきたデータ(body)をストロングパラメータを経由して@tweetに代入
    @tweet.user_id = current_user.id # user_idの情報はフォームからはきていないので、deviseのメソッドを使って「ログインしている自分のid」を代入
    @tweet.save
    redirect_to tweets_path
    
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to :action => "show", :id => @tweet.id
    else
      redirect_to :action => "new"
    end
  end  

  def destroy
    Tweet.find(params[:id]).destroy
    redirect_to action: :index
  end

  def top
  end  

  def tag
    params[:tag_id].present? ? Tag.find(params[:tag_id]).tweets : Tweet.all

  end  

  private
  def tweet_params
    params.require(:tweet).permit(:body,:country,:image,tag_ids: []) # tweetモデルのカラムのみを許可
  end

  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    @favorite_tweets = @user.favorite_tweets
    @good_tweets = @user.good_tweets
    @bad_tweets = @user.bad_tweets
  end

  def top
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bads_helper.rb
module BadsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bads/create.html.erb
<h1>Bads#create</h1>
<p>Find me in app/views/bads/create.html.erb</p>

app/views/bads/destroy.html.erb
<h1>Bads#destroy</h1>
<p>Find me in app/views/bads/destroy.html.erb</p>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/goods/create.html.erb
<h1>Goods#create</h1>
<p>Find me in app/views/goods/create.html.erb</p>

app/views/goods/destroy.html.erb
<h1>Goods#destroy</h1>
<p>Find me in app/views/goods/destroy.html.erb</p>

app/views/tweets/_form.html.erb
<%= stylesheet_link_tag 'tweets_form', :media => "all" %>

<div class ="tweet-form">
  <div class="tweet-main">
　  <%= form_for @tweet do |f| %>
      <p>
        <%= f.select :country, [["アメリカ", "アメリカ"], ["イギリス", "イギリス"],["日本","日本"],["フランス","フランス"],["イタリア","イタリア"],["ドイツ","ドイツ"],["オランダ","オランダ"],["スイス","スイス"],["スウェーデン","スウェーデン"],["スペイン","スペイン"],["チェコ","チェコ"],["ポルトガル","ポルトガル"],["ロシア","ロシア"],["ベルギー","ベルギー"],["エジプト","エジプト"],["インド","インド"],["中国","中国"],["韓国","韓国"],["その他","その他"]], include_blank: "国を選択して下さい" %>
      </p>
      <p>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %> 
          <%= tag.label do %>
            <%= tag.check_box %>
            <%= tag.text %>
          <% end %>
        <% end %>
      </p>
    
      <div class="field">
        <%= f.label :画像 %>
        <%= f.file_field :image %>
      </div>

      <p class ="tweetBody">
        <%= f.label :body,"内容" %>
        <%= f.text_area :body, size: "60x10" %>
      </p>
      <div class="button">
        <%= f.submit '投稿する' %>
      </div> 
      
    <% end %> 
  </div>    
</div>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>

app/views/tweets/edit.html.erb
<h2>編集</h2>

<%= render "form" %>


app/views/tweets/index.html.erb
<%= stylesheet_link_tag 'tweets_index', :media => "all" %>

<div class = search>
  <div class="search-container">
    <p class="title">Search</p>
    <div class= "keyword">
      <%= search_form_for @q do |f| %>
        <%= f.label :body, "Keyword" %>
        <%= f.search_field :body_cont %>
        <%= f.submit "検索" %>  
      <% end %>
    </div>
   <hr>
    <div class="era"> 
      <%= form_tag tweets_path, method: :get, class: 'boards__searchForm' do %>
       <%= select_tag :tag_id,
                 options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                 {
                   prompt: '年代で検索',
                   onchange: 'submit(this.form);'
                 }
         %>
      <% end %>
    </div> 
  </div>
</div>
<div class="tweets">
 <% @tweets.each do |tweet| %>
    
    <div class="tweet-container">
      <p class = "name"><%=link_to tweet.user.name, user_path(tweet.user.id) %></p>
      <p>
        <if t.image >
          <%= image_tag tweet.image_url,:size => '150×150' %> 
         
        <end>
      </p>  
      <p><span>国：</span><%= tweet.country %></p>
      <p>
       <span>年代:</span>
       <% tweet.tags.each do |tag| %>
        <%= tag.name %>
       <% end %>
      </p>   
      <p><%=link_to tweet.body, tweet_path(tweet.id) %></p>
     

     <div class = "tweet-check">
      <% if user_signed_in? %>
      <% if tweet.favorited_by?(current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
        <p><span>◯: </span><%=link_to tweet.favorites.count, tweet_favorites_path(tweet.id), method: :delete %></p>
       <% else %>
        <p><span>◯: </span><%=link_to tweet.favorites.count, tweet_favorites_path(tweet.id), method: :post %></p>
       <% end %>
      <% else %>
       <p><span>◯: </span><%= tweet.favorites.count %></p>
      <% end %>
      <% if user_signed_in? %>
      <% if tweet.gooded_by?(current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
        <p><span>△: </span><%=link_to tweet.goods.count, tweet_goods_path(tweet.id), method: :delete %></p>
       <% else %>
        <p><span>△: </span><%=link_to tweet.goods.count, tweet_goods_path(tweet.id), method: :post %></p>
       <% end %>
      <% else %>
       <p><span>△: </span><%= tweet.goods.count %></p>
      <% end %>
      <% if user_signed_in? %>
      <% if tweet.baded_by?(current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
        <p><span>✕: </span><%=link_to tweet.bads.count, tweet_bads_path(tweet.id), method: :delete %></p>
       <% else %>
        <p><span>✕: </span><%=link_to tweet.bads.count, tweet_bads_path(tweet.id), method: :post %></p>
       <% end %>
      <% else %>
       <p><span>✕: </span><%= tweet.bads.count %></p>
      <% end %>
     </div> 

     <div class="tweet-edit-delete">
      <% if user_signed_in? && tweet.user_id == current_user.id %>
       <%= link_to "編集する", edit_tweet_path(tweet.id) %>
       <%= link_to "削除する", tweet_path(tweet.id), method: :delete %>
      <% end %>
     </div>  
    </div>  
 <% end %>
</div> 

app/views/tweets/new.html.erb
<h1> 新規投稿</h1>



<%= render "form" %>

app/views/tweets/show.html.erb
<%= stylesheet_link_tag 'tweet_show', :media => "all" %>
 
<div class ="tweet">
 <p><span>name: </span><%= @user.name %></p>

 <if t.image >
      <%= image_tag @tweet.image_url,:size => '400×350' %> 
     <end> 
 <p>
  <span>年代:</span>
  <% @tweet.tags.each do |tag| %>
     <%= tag.name %>
  <% end %>
 </p>
 <p><span>国：</span><%= @tweet.country %></p>
 <p><span>内容：</span><%= @tweet.body %></p>
 <div class = "tweet-check">
      
      
       <p><span>◯: </span><%= @tweet.favorites.count %></p>
      
       <p><span>△: </span><%= @tweet.goods.count %></p>
      
       <p><span>✕: </span><%= @tweet.bads.count %></p>
      
   </div> 

 <% if user_signed_in? && @tweet.user_id == current_user.id %>
       <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
       <%= link_to "削除する", tweet_path(@tweet.id), method: :delete %>
      <% end %>
</div>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.name unless c.user.blank? %>
      <br>
      <%= c.comment %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :comment%>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
   

app/views/users/index.html.erb
<%= stylesheet_link_tag 'users_index', :media => "all" %>

<h1>ユーザー一覧</h1>

<div class="user">
  <div class = "user-container">
   <% @users.each do |user| %>
      <p class="user-name"><%=link_to user.name, user_path(user.id) %></p>
   <% end %>
  </div> 
</div>  

app/views/users/show.html.erb
<%= stylesheet_link_tag 'users_show', :media => "all" %>

<p class="name"><%= @user.name %><span>さんのマイページ</span></p>
<div class="my-tweets">
  <div class="my-tweets-container user">
    <h1><%= @user.name %>さんの投稿</h1>
    <% @tweets.each do |tweet| %>
     <div class="my-tweets-container-box"> 
      <div class = "tweet-image">
        <if t.image >
          <%= image_tag tweet.image_url,:size => '100×50' %> 
        <end>
      </div>
      <div class ="tweet-letter"> 
        <p><span>国：</span><%= tweet.country %></p>
        <p>
          <span>年代:</span>
          <% tweet.tags.each do |tag| %>
            <%= tag.name %>
          <% end %>
        </p>   
        <p><%=link_to tweet.body, tweet_path(tweet.id) %></p>
        <div class = "tweet-check">
          <p><span>◯: </span><%= tweet.favorites.count %></p>
          <p><span>△: </span><%= tweet.goods.count %></p>
          <p><span>✕: </span><%= tweet.bads.count %></p>
        </div>
        <div class = "tweet-edit-delete"> 
         <% if user_signed_in? && tweet.user_id == current_user.id %>
           <%= link_to "編集する", edit_tweet_path(tweet.id) %>
           <%= link_to "削除する", tweet_path(tweet.id), method: :delete %>
         <% end %>
        </div>
      </div> 
      
     </div>  
    <% end %>
         
  </div>   
 
  <div class="my-tweets-container check">
    <h1>〇△投稿</h1>
    <% @favorite_tweets.each do |tweet| %>
     <div class="my-tweets-container-box">  
      <p class="tweet-image">
        <if t.image >
          <%= image_tag tweet.image_url,:size => '100×50' %> 
        <end>
      </p>
      <div class ="tweet-letter"> 
        <p><span>国：</span><%= tweet.country %></p> 
        <p>
          <span>年代:</span>
            <% tweet.tags.each do |tag| %>
              <%= tag.name %>
            <% end %>
        </p>   
        <p><%=link_to tweet.body, tweet_path(tweet.id) %></p>
        <div class = "tweet-check">
          <p><span>◯: </span><%= tweet.favorites.count %></p>
          <p><span>△: </span><%= tweet.goods.count %></p>
          <p><span>✕: </span><%= tweet.bads.count %></p>      
        </div> 
      </div>  
      
     </div> 
    <% end %>
    <% @good_tweets.each do |tweet| %> 
     <div class="my-tweets-container-box">  
      <p class="tweet-image">
        <if t.image >
          <%= image_tag tweet.image_url,:size => '100×50' %> 
        <end>
      </p>
      <div class ="tweet-letter"> 
        <p><span>国：</span><%= tweet.country %></p> 
        <p>
          <span>年代:</span>
          <% tweet.tags.each do |tag| %>
            <%= tag.name %>
          <% end %>
        </p>   
        <p><%=link_to tweet.body, tweet_path(tweet.id) %></p>
        <div class = "tweet-check">
          <p><span>◯: </span><%= tweet.favorites.count %></p>
          <p><span>△: </span><%= tweet.goods.count %></p>
          <p><span>✕: </span><%= tweet.bads.count %></p>
        </div>
      </div> 
     
     </div> 
    <% end %>

  </div> 
</div>