config/routes.rb
Rails.application.routes.draw do
  
  
 
 
 

  devise_for :users

  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    resource :goods, only: [:create, :destroy]
    resource :bads, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  root 'tweets#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bad.rb
class Bad < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/good.rb
class Good < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tweet_tags, dependent: :destroy
    has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :favorites
    has_many :goods
    has_many :bads
    mount_uploader :image, ImageUploader
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
    def gooded_by?(user)
        goods.where(user_id: user.id).exists?
    end
    def baded_by?(user)
        bads.where(user_id: user.id).exists?
    end        
    has_many :tweet_tags, dependent: :destroy
    has_many :tags, through: :tweet_tags

    default_scope -> { order(created_at: :desc) }
    
    has_many :comments, dependent: :destroy
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
    belongs_to :tweet
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :name, presence: true
         
   has_many :tweets
   has_many :favorites
   has_many :favorite_tweets, through: :favorites, source: :tweet

   has_many :goods
   has_many :good_tweets, through: :goods, source: :tweet
   has_many :bads
   has_many :bad_tweets, through: :bads, source: :tweet
   
   has_many :comments, dependent: :destroy

end

app/controllers/bads_controller.rb
class BadsController < ApplicationController
  def create
    bad = current_user.bads.build(tweet_id: params[:tweet_id])
    bad.save
    redirect_to tweets_path

    if @good= Good.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
      @good.destroy
    end
    if @favorite= Favorite.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
      @favorite.destroy
    end
  end

  def destroy
    bad = Bad.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    bad.destroy
    redirect_to tweets_path
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def create
    good = current_user.goods.build(tweet_id: params[:tweet_id])
    good.save
    redirect_to tweets_path

    if @bad= Bad.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
      @bad.destroy
    end
    if @favorite= Favorite.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
      @favorite.destroy
    end


  end

  def destroy
    good = Good.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    good.destroy
    redirect_to tweets_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    @favorite_tweets = @user.favorite_tweets
    @good_tweets = @user.good_tweets
    @bad_tweets = @user.bad_tweets
  end

  def top
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bads_helper.rb
module BadsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vintagehurugi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.google.com/specimen/IM+Fell+Double+Pica?preview.size=60&selection.family=IM+Fell+Double+Pica#standard-styles" rel="stylesheet">
    
  </head>

  <body>
  
   <header>
    <h1 class="header-title">ONKOCHISHIN</h1>
    <div class="header-list">
     <ul>
      <% if user_signed_in? %>  <!-- deviseのメソッドで、「ログインしているかしていないかでtrue or falseを返す」メソッド -->
        <li><%= link_to "新規投稿", new_tweet_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "マイページ", user_path(current_user.id) %></li>
        <li><%= link_to "ツイート一覧", tweets_path %></li>
        <li><%= link_to "ユーザー一覧", users_path %></li>
      <% else %>
      <!-- <li><%= link_to "新規登録", new_user_registration_path %></li> -->
      <!--   <li><%= link_to "ログイン", new_user_session_path %></li> -->
      <% end %>   
     </ul>   
    </div>
   </header>
   <footer>
      <p class ="footer-letter">Copyright © 2020 KoshiroKataoka All Rights Reserved.</p>
   </footer>
   

   
    
    <%= yield %>

  </body>
</html>